### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by Ukhupacha** [fundamentalvision/Deformable-DETR#119]
Hi,

Is the Python test supposed to run all the way? Cause I can't make it run with going for 1025 channels

$ python test.py 
* True check_forward_equal_with_pytorch_double: max_abs_err 8.67e-19 max_rel_err 2.35e-16
* True check_forward_equal_with_pytorch_float: max_abs_err 4.66e-10 max_rel_err 1.13e-07
* True check_gradient_numerical(D=30)
* True check_gradient_numerical(D=32)
* True check_gradient_numerical(D=64)
* True check_gradient_numerical(D=71)
Traceback (most recent call last):
  File "test.py", line 88, in <module>
    check_gradient_numerical(channels, True, True, True)
  File "test.py", line 78, in check_gradient_numerical
    gradok = gradcheck(func, (value.double(), shapes, level_start_index, sampling_locations.double(), attention_weights.double(), im2col_step))
  File "/data/ukhu/Apps/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 1263, in gradcheck
    return _gradcheck_helper(**args)
  File "/data/ukhu/Apps/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 1277, in _gradcheck_helper
    rtol, atol, check_grad_dtypes, check_forward_ad=check_forward_ad, nondet_tol=nondet_tol)
  File "/data/ukhu/Apps/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 947, in _gradcheck_real_imag
    rtol, atol, check_grad_dtypes, nondet_tol)
  File "/data/ukhu/Apps/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 991, in _slow_gradcheck
    analytical = _check_analytical_jacobian_attributes(tupled_inputs, o, nondet_tol, check_grad_dtypes)
  File "/data/ukhu/Apps/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 537, in _check_analytical_jacobian_attributes
    reentrant = _check_jacobians_equal(jacobians1, jacobians2, nondet_tol)
  File "/data/ukhu/Apps/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 467, in _check_jacobians_equal
    if j1_x.numel() != 0 and (j1_x - j2_x).abs().max() > atol:
RuntimeError: CUDA out of memory. Tried to allocate 1.88 GiB (GPU 0; 11.77 GiB total capacity; 9.41 GiB already allocated; 444.06 MiB free; 9.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Or should I empty some variables before running the whole loop?

Thanks in advance

**Comment by demidovd98** [comment]
Also had the same issue. I guess this test is for multiple GPUs with combined memory.
I simply commented out the tests my GPU's memory is not enough for, just to check the rest of the tests.

Training also worked after I did that, so I think the test is not critical.

**Comment by lijain** [comment]
The problem I'm having doesn't seem to be the same, it's slow to detect. It feels like the cpu is not running so slowly, do you encounter this situation?
* True check_forward_equal_with_pytorch_double: max_abs_err 8.67e-19 max_rel_err 2.35e-16
* True check_forward_equal_with_pytorch_float: max_abs_err 4.66e-10 max_rel_err 1.13e-07
* True check_gradient_numerical(D=30)
* True check_gradient_numerical(D=32)
* True check_gradient_numerical(D=64)

**Comment by amirhesamyazdi** [comment]
@Ukhupacha Did you fix your issue? Could you train without a fuss after fixing the test?
What size of image you are mostly dealing with? Thanks.

**Comment by xiejialong** [comment]
I got the same problem! Maybe, my 1080Ti haven't enough memory

**Comment by nagidvil** [comment]
me 2 :(
