### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Fyw1988** [fundamentalvision/Deformable-DETR#159]
When I use 'GPUS_PER_NODE=1 ./tools/run_dist_launch.sh 1 ./configs/r50_deformable_detr.sh' to try to train on the coco dataset, The following error occurred:

Start training
Traceback (most recent call last):
  File "/home/ding/fyw/Deformable-DETR-main/main.py", line 326, in <module>
    main(args)
  File "/home/ding/fyw/Deformable-DETR-main/main.py", line 275, in main
    train_stats = train_one_epoch(
  File "/home/ding/fyw/Deformable-DETR-main/engine.py", line 37, in train_one_epoch
    prefetcher = data_prefetcher(data_loader, device, prefetch=True)
  File "/home/ding/fyw/Deformable-DETR-main/datasets/data_prefetcher.py", line 21, in __init__
    self.preload()
  File "/home/ding/fyw/Deformable-DETR-main/datasets/data_prefetcher.py", line 25, in preload
    self.next_samples, self.next_targets = next(self.loader)
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ding/fyw/Deformable-DETR-main/datasets/coco.py", line 34, in __getitem__
    img, target = super(CocoDetection, self).__getitem__(idx)
  File "/home/ding/fyw/Deformable-DETR-main/datasets/torchvision_datasets/coco.py", line 75, in __getitem__
    path = coco.loadImgs(img_id)[0]['file_name']
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/pycocotools/coco.py", line 230, in loadImgs
    return [self.imgs[id] for id in ids]
  File "/home/ding/anaconda3/envs/yolov5/lib/python3.9/site-packages/pycocotools/coco.py", line 230, in <listcomp>
    return [self.imgs[id] for id in ids]
KeyError: '0'

Traceback (most recent call last):
  File "/home/ding/fyw/Deformable-DETR-main/./tools/launch.py", line 201, in <module>
    main()
  File "/home/ding/fyw/Deformable-DETR-main/./tools/launch.py", line 196, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['./configs/r50_deformable_detr.sh']' returned non-zero exit status 1.

It looks like a data and read error, but I don't know why.Has anyone experienced this error?

**Comment by Fyw1988** [comment]
I have completed the compilation according to the steps of the github.

**Comment by PaiDaxing114514** [comment]
I had the same problem. Did you solve it

**Comment by chengxug** [comment]
I also encountered this issue. Although imgid exists in my JSON file, the program raises a KeyError. Eventually, I discovered the problem was that my imgid was stored as a string type in the JSON file, while the program expects an integer type.
The issue is caused by the following code:
```python
def loadImgs(self, ids=[]):
        """
        Load anns with the specified ids.
        :param ids (int array)       : integer ids specifying img
        :return: imgs (object array) : loaded img objects
        """
        if _isArrayLike(ids):
            return [self.imgs[id] for id in ids]
        elif type(ids) == int:
            return [self.imgs[ids]]
```
This code loads images using the image ID. When imgid is an integer, it correctly returns the image via self.imgs[ids]. However, when imgid is a string type, it's mistakenly treated as an iterable (since strings are iterable in Python). As a result, the code enters the if branch incorrectly and attempts to iterate through the string characters, using each character as a key to look up images, which leads to the KeyError.
