### ISSUE TITLE
RuntimeError: Not implemented on the CPU

### ISSUE THREAD

**Issue by skyfallsss** [fundamentalvision/Deformable-DETR#166]
Traceback (most recent call last):
  File "/home/kemosheng/Deformable-DETR-main/vis_.py", line 95, in <module>
    outputs = model(img)
  File "/home/kemosheng/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kemosheng/Deformable-DETR-main/models/deformable_detr.py", line 157, in forward
    hs, init_reference, inter_references, enc_outputs_class, enc_outputs_coord_unact = self.transformer(srcs, masks, pos, query_embeds)
  File "/home/kemosheng/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kemosheng/Deformable-DETR-main/models/deformable_transformer.py", line 153, in forward
    memory = self.encoder(src_flatten, spatial_shapes, level_start_index, valid_ratios, lvl_pos_embed_flatten, mask_flatten)
  File "/home/kemosheng/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kemosheng/Deformable-DETR-main/models/deformable_transformer.py", line 256, in forward
    output = layer(output, pos, reference_points, spatial_shapes, level_start_index, padding_mask)
  File "/home/kemosheng/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kemosheng/Deformable-DETR-main/models/deformable_transformer.py", line 221, in forward
    src2 = self.self_attn(self.with_pos_embed(src, pos), reference_points, src, spatial_shapes, level_start_index, padding_mask)
  File "/home/kemosheng/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kemosheng/Deformable-DETR-main/models/ops/modules/ms_deform_attn.py", line 112, in forward
    output = MSDeformAttnFunction.apply(
  File "/home/kemosheng/Deformable-DETR-main/models/ops/functions/ms_deform_attn_func.py", line 26, in forward
    output = MSDA.ms_deform_attn_forward(
RuntimeError: Not implemented on the CPU

**Comment by Tzeny** [comment]
Pls fix, thx

**Comment by HaithemH** [comment]
Is there a fix ?

**Comment by Tzeny** [comment]
For the library I was using I found a CPU implementation in the same file as the CUDA one, they probably used it for debugging, but it worked fine.

**Comment by YuMJie** [comment]
> For the library I was using I found a CPU implementation in the same file as the CUDA one, they probably used it for debugging, but it worked fine.

could you provide the code for me? thank you !

**Comment by ChrisL97** [comment]
at `main.py`, change `--device` to `cuda` if u have cuda support
```
parser.add_argument('--device', default='cuda', help='device to use for training / testing')
```
damn this sh!t wasted me 2 hrs
