### ISSUE TITLE
 %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by jinluo12345** [fundamentalvision/Deformable-DETR#184]
when I download MSDA an error raised:
(pytorch) D:\DeepLearning\models\cv\object detection\detr improvements\Deformable-DETR\models\ops>python test.py
Traceback (most recent call last):
  File "D:\DeepLearning\models\cv\object detection\detr improvements\Deformable-DETR\models\ops\test.py", line 18, in <module>
    from functions.ms_deform_attn_func import MSDeformAttnFunction, ms_deform_attn_core_pytorch
  File "D:\DeepLearning\models\cv\object detection\detr improvements\Deformable-DETR\models\ops\functions\__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "D:\DeepLearning\models\cv\object detection\detr improvements\Deformable-DETR\models\ops\functions\ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: DLL load failed while importing MultiScaleDeformableAttention: %1 不是有效的 Win32 应用程序。
I do not know why

**Comment by wry777** [comment]
同问
