### ISSUE TITLE
error in ms_deformable_col2im_cuda: too many resources requested for launch

### ISSUE THREAD

**Issue by kritiyer** [fundamentalvision/Deformable-DETR#82]
I was able to compile the cuda ops using sh make.sh, but when I ran the unit test, I got the following error:

```
error in ms_deformable_col2im_cuda: too many resources requested for launch
Traceback (most recent call last):
  File "test.py", line 86, in <module>
    check_gradient_numerical(channels, True, True, True)
  File "test.py", line 76, in check_gradient_numerical
    gradok = gradcheck(func, (value.double(), shapes, level_start_index, sampling_locations.double(), attention_weights.double(), im2col_step))
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 291, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 229, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.2267, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2267, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2267]],
       dtype=torch.float64)
analytical:tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)
```

I am using CUDA 10.2, pytorch 1.5.1, and torchvision 0.6.0 with a single NVIDIA Tesla K80 GPU. Does anyone know what the issue could be?

**Comment by kahuku** [comment]
I'm having the same issue but using CUDA 11.2.

**Comment by rlit** [comment]
Same here, using v100 with 16GB

**Comment by Jianqiuer** [comment]
Same here, using v100 

What problem caused it？

**Comment by florinshen** [comment]
same here, using Tesla v100 and cuda11.2

**Comment by noahcao** [comment]
Same here on A100:

Pytorch 1.8.0
CUDA 11.2

**Comment by WenmuZhou** [comment]
Same here on V100:

Pytorch 1.8.1
CUDA 11.2

**Comment by whdcode** [comment]
cuda111m torch1.7
* False check_forward_equal_with_pytorch_double: max_abs_err 1.26e-01 max_rel_err 2.87e+01
* False check_forward_equal_with_pytorch_float: max_abs_err 8.95e-02 max_rel_err 2.18e+01
Traceback (most recent call last):
  File "test.py", line 88, in <module>
    check_gradient_numerical(channels, True, True, True)
  File "test.py", line 78, in check_gradient_numerical
    gradok = gradcheck(func, (value.double(), shapes, level_start_index, sampling_locations.double(), attention_weights.double(), im2col_step))
  File "/home/wuhuidong/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 390, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "/home/wuhuidong/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 372, in checkIfNumericalAnalyticAreClose
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "/home/wuhuidong/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 289, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 1,
numerical:tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)
analytical:tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)

**Comment by KeyKy** [comment]
same problem

**Comment by Zhaozeyong** [comment]
Same here, using v100

**Comment by anotheryia** [comment]
using v100 too, seems like use up memory, nvidia shows memory increase to 10GB and then the error shows up.
channels from 30 to 71 ok, 1025  crash.
